name: "Run Terragrunt Plan"
description: "Runs terragrunt plan in a specified directory"
inputs:
  path:
    description: "The path to the directory containing terragrunt.hcl"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2

    - name: Install Terragrunt
      run: |
        curl -L https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 \
        -o /usr/local/bin/terragrunt
        chmod +x /usr/local/bin/terragrunt

    - name: Run terragrunt plan
      working-directory: ${{ inputs.path }}
      run: terragrunt plan
