name: Atomic Runner
on:
  workflow_dispatch:
    inputs:
      directory:
        description: "Directory where terragrunt.hcl changed"
        required: true
        type: string

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run terragrunt
        run: |
          echo "${{ github.event.inputs.directory }}"
          cd ${{ github.event.inputs.directory }}
          echo "${{ github.event.inputs.directory }}"
