name: Change Detector
on:
  push:
    branches:
      - main
    paths:
      - "environments/**/*.hcl"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Identify changed directories
        id: changes
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep 'environments/.*terragrunt.hcl' || true)

          CHANGED_DIRS=$(echo "$CHANGED_FILES" | xargs -I{} dirname {} | sort -u)

          echo "changed_dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      - name: Trigger Atomic Runner workflows
        if: ${{ steps.changes.outputs.changed_dirs != '' }}
        run: |
          for dir in ${{ steps.changes.outputs.changed_dirs }}
          do
            echo "Dispatching workflow for directory: $dir"

            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/atomic-runner.yml/dispatches \
              -d "{\"ref\":\"main\", \"inputs\":{\"directory\":\"$dir\"}}"
          done
