name: Terragrunt Workflow

on:
  push:
    paths:
      - "environments/*/*/terragrunt.hcl"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.detect_changes.outputs.changed_dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect changed directories
        id: detect_changes
        run: |
          changed_files=$(echo "${{ toJson(github.event.head_commit) }}" | jq -r '[.modified[], .added[]] | unique[]' | grep 'terragrunt.hcl' || true)

          if [ -z "$changed_files" ]; then
            changed_dirs_json='[]'
          else
            changed_dirs=$(echo "$changed_files" | xargs -n1 dirname | sort -u)
            changed_dirs_json=$(echo "$changed_dirs" | jq -R . | jq -s .)
          fi

          echo "changed_dirs=$changed_dirs_json" >> $GITHUB_OUTPUT

  terragrunt:
    runs-on: ubuntu-latest
    needs: detect-changes
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.detect-changes.outputs.changed_dirs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: TerragruntTEST
        run: |
          echo "Directory: ${{ matrix.dir }}"
